const array = [
  {
    "id": "1",
    "title": "My Dark Vanessa",
    "author": "Kate Elizabeth Russell",
    "genre": "Drama",
    "progress": "66",
    "last_opened": "6 Month Ago",
    "src": "/img5.jpg",
  },
  {
    id: "2",
    title: "50 Shades of Grey",
    author: "E.L. James",
    genre: "Romance",
    progress: "40",
    last_opened: "5 Days Ago",
    src: "/img9.jpg",
  },
  {
    id: "3",
    title: "Tears of Endurance",
    author: "D.G. Torrens",
    genre: "Drama",
    progress: "55",
    last_opened: "Last Week",
    src: "/img1.jpg",
  },
  {
    id: "4",
    title: "Harry Potter and the Cur..",
    author: "J. K. Rowling",
    genre: "Drama",
    progress: "66",
    last_opened: "2 Weeks Ago",
    src: "/img2.jpg",
  },
  {
    id: "5",
    title: "Broken Things",
    author: "Lauren Oliver",
    genre: "Drama",
    progress: "15",
    last_opened: "2 Month Ago",
    src: "/img3.jpg",
  },
  {
    id: "6",
    title: "Baaz",
    author: "Anuja Chauhan",
    genre: "Drama",
    progress: "79",
    last_opened: "3 Days Ago",
    src: "/img6.jpg",
  },
  {
    id: "7",
    title: "The Outsider",
    author: "Stephen King",
    genre: "Mystery",
    progress: "49",
    last_opened: "1 Hour Ago",
    src: "/img13.jpg",
  },
  {
    id: "8",
    title: "Pride and Prejudice",
    author: "Jane Austen",
    genre: "Romance",
    progress: "52",
    last_opened: "2 Days Ago",
    src: "/img10.jpg",
  },
  {
    id: "9",
    title: "The Hitchhiker's Guide",
    author: "Douglas Adams",
    genre: "Comedy",
    progress: "35",
    last_opened: "A Week Ago",
    src: "/img8.webp",
  },
  {
    id: "10",
    title: "The Legend of Korra",
    author: "Michael Dante DiMartino",
    genre: "Animation",
    progress: "100",
    last_opened: "A Month Ago",
    src: "/img15.jpg",
  },
  {
    id: "11",
    title: "The House Uptown",
    author: "Melissa Ginsburg",
    genre: "Drama",
    progress: "25",
    last_opened: "3 Weeks Ago",
    src: "/img4.jpg",
  },
  {
    id: "12",
    title: "Producing with Passion",
    author: "Dorothy Fadiman",
    genre: "Documentary",
    progress: "71",
    last_opened: "3 Month Ago",
    src: "/img14.jpg",
  },
  {
    id: "13",
    title: "ArchAngel's Kiss",
    author: "Nalini Singh",
    genre: "Action",
    progress: "0",
    last_opened: "3 Weeks Ago",
    src: "/img12.jpg",
  },
  {
    id: "14",
    title: "Furiously Happy",
    author: "Jenny Lawson",
    genre: "Comedy",
    progress: "75",
    last_opened: "15 Minutes Ago",
    src: "/img7.webp",
  },
  {
    id: "15",
    title: "Breaking Point",
    author: "Pamela Calare",
    genre: "Action",
    progress: "100",
    last_opened: "Yestertad",
    src: "/img11.jpg",
  },
];

export default array;
